const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const mongoose = require('./db');
var tableController = require('./Controllers/TableController')
var menuController = require('./Controllers/MenuController')
var bookingController = require('./Controllers/BookingController')
var app = express()
app.use(bodyParser.json())
app.use(cors({origin: 'http://localhost:4200'}))
app.listen(3000,() => console.log('Expresjs Connected'))
app.use('/', tableController)
app.use('/', menuController)
app.use('/', bookingController)